package db

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"time"
)

// ── Types ─────────────────────────────────────────────────────────────────────

// Session represents a persisted chat/agent session.
type Session struct {
	ID         string
	BookDir    string
	ChapterNum int
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// Message represents a single message within a session.
type Message struct {
	ID        string
	SessionID string
	Role      string // "user", "assistant", or "tool"
	Content   string
	TokensIn  int
	TokensOut int
	Model     string
	CreatedAt time.Time
}

// Job represents a queued background job.
type Job struct {
	ID          string
	Type        string
	BookDir     string
	ChapterNum  int
	Payload     string // raw JSON
	Status      string // pending|running|done|failed|cancelled
	Priority    int
	Batch       bool
	Result      string // JSON on success
	Error       string // message on failure
	Attempt     int
	MaxAttempts int
	CreatedAt   time.Time
	StartedAt   *time.Time
	FinishedAt  *time.Time
}

// ── Sessions ──────────────────────────────────────────────────────────────────

// CreateSession inserts a new session row and returns its ID.
// The ID is a UUID generated by the caller (pass from uuid.NewString()).
func CreateSession(db *sql.DB, id, bookDir string, chapterNum int) error {
	_, err := db.Exec(
		`INSERT INTO sessions(id, book_dir, chapter_num) VALUES (?, ?, ?)`,
		id, bookDir, chapterNum,
	)
	return err
}

// GetSession returns a session by ID.
func GetSession(db *sql.DB, id string) (*Session, error) {
	row := db.QueryRow(
		`SELECT id, book_dir, chapter_num, created_at, updated_at FROM sessions WHERE id = ?`, id,
	)
	var s Session
	if err := row.Scan(&s.ID, &s.BookDir, &s.ChapterNum, &s.CreatedAt, &s.UpdatedAt); err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("session %s not found", id)
		}
		return nil, err
	}
	return &s, nil
}

// ListSessions returns sessions for a book directory, ordered by most recent first.
func ListSessions(db *sql.DB, bookDir string, limit int) ([]Session, error) {
	if limit <= 0 {
		limit = 20
	}
	rows, err := db.Query(
		`SELECT id, book_dir, chapter_num, created_at, updated_at
		 FROM sessions WHERE book_dir = ?
		 ORDER BY created_at DESC LIMIT ?`,
		bookDir, limit,
	)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var sessions []Session
	for rows.Next() {
		var s Session
		if err := rows.Scan(&s.ID, &s.BookDir, &s.ChapterNum, &s.CreatedAt, &s.UpdatedAt); err != nil {
			return nil, err
		}
		sessions = append(sessions, s)
	}
	return sessions, rows.Err()
}

// TouchSession updates the updated_at timestamp on a session.
func TouchSession(db *sql.DB, id string) error {
	_, err := db.Exec(`UPDATE sessions SET updated_at = CURRENT_TIMESTAMP WHERE id = ?`, id)
	return err
}

// DeleteSession removes a session and its messages (cascade).
func DeleteSession(db *sql.DB, id string) error {
	_, err := db.Exec(`DELETE FROM sessions WHERE id = ?`, id)
	return err
}

// ── Messages ──────────────────────────────────────────────────────────────────

// AppendMessage inserts a new message into a session.
// The id should be a UUID generated by the caller.
func AppendMessage(db *sql.DB, id, sessionID, role, content, model string, tokIn, tokOut int) error {
	_, err := db.Exec(
		`INSERT INTO messages(id, session_id, role, content, model, tokens_in, tokens_out)
		 VALUES (?, ?, ?, ?, ?, ?, ?)`,
		id, sessionID, role, content, model, tokIn, tokOut,
	)
	return err
}

// GetSessionMessages returns all messages for a session, ordered by creation time.
func GetSessionMessages(db *sql.DB, sessionID string) ([]Message, error) {
	rows, err := db.Query(
		`SELECT id, session_id, role, content, tokens_in, tokens_out, model, created_at
		 FROM messages WHERE session_id = ? ORDER BY created_at ASC`,
		sessionID,
	)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var msgs []Message
	for rows.Next() {
		var m Message
		if err := rows.Scan(&m.ID, &m.SessionID, &m.Role, &m.Content,
			&m.TokensIn, &m.TokensOut, &m.Model, &m.CreatedAt); err != nil {
			return nil, err
		}
		msgs = append(msgs, m)
	}
	return msgs, rows.Err()
}

// ── Jobs ──────────────────────────────────────────────────────────────────────

// EnqueueJob inserts a new job and returns its ID.
// id should be a UUID generated by the caller.
// payload is any JSON-serialisable value.
func EnqueueJob(db *sql.DB, id, jobType, bookDir string, chapterNum int, payload any, batch bool, priority int) error {
	payloadJSON, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("enqueue: marshal payload: %w", err)
	}
	_, err = db.Exec(
		`INSERT INTO jobs(id, type, book_dir, chapter_num, payload, batch, priority)
		 VALUES (?, ?, ?, ?, ?, ?, ?)`,
		id, jobType, bookDir, chapterNum, string(payloadJSON), batch, priority,
	)
	return err
}

// DequeueJob atomically claims the highest-priority pending job, setting its
// status to "running". Returns nil if the queue is empty.
func DequeueJob(db *sql.DB) (*Job, error) {
	tx, err := db.Begin()
	if err != nil {
		return nil, err
	}
	defer tx.Rollback() //nolint:errcheck

	row := tx.QueryRow(
		`SELECT id FROM jobs WHERE status = 'pending'
		 ORDER BY priority DESC, created_at ASC LIMIT 1`,
	)
	var jobID string
	if err := row.Scan(&jobID); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}

	if _, err := tx.Exec(
		`UPDATE jobs SET status = 'running', started_at = CURRENT_TIMESTAMP,
		                 attempt = attempt + 1 WHERE id = ?`, jobID,
	); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	return GetJob(db, jobID)
}

// UpdateJobStatus updates the status, result, and error fields of a job.
// On terminal states (done/failed/cancelled) it also sets finished_at.
func UpdateJobStatus(db *sql.DB, id, status, result, errMsg string) error {
	switch status {
	case "done", "failed", "cancelled":
		_, err := db.Exec(
			`UPDATE jobs SET status = ?, result = ?, error = ?,
			                 finished_at = CURRENT_TIMESTAMP WHERE id = ?`,
			status, result, errMsg, id,
		)
		return err
	default:
		_, err := db.Exec(
			`UPDATE jobs SET status = ?, result = ?, error = ? WHERE id = ?`,
			status, result, errMsg, id,
		)
		return err
	}
}

// GetJob returns a job by ID.
func GetJob(db *sql.DB, id string) (*Job, error) {
	row := db.QueryRow(
		`SELECT id, type, book_dir, chapter_num, payload, status, priority, batch,
		        result, error, attempt, max_attempts, created_at, started_at, finished_at
		 FROM jobs WHERE id = ?`, id,
	)
	return scanJob(row)
}

// ListJobs returns jobs filtered by status ("" = all statuses), ordered by
// priority DESC then creation time ASC.
func ListJobs(db *sql.DB, status string, limit int) ([]Job, error) {
	if limit <= 0 {
		limit = 50
	}

	var (
		rows *sql.Rows
		err  error
	)
	if status == "" {
		rows, err = db.Query(
			`SELECT id, type, book_dir, chapter_num, payload, status, priority, batch,
			        result, error, attempt, max_attempts, created_at, started_at, finished_at
			 FROM jobs ORDER BY priority DESC, created_at ASC LIMIT ?`, limit,
		)
	} else {
		rows, err = db.Query(
			`SELECT id, type, book_dir, chapter_num, payload, status, priority, batch,
			        result, error, attempt, max_attempts, created_at, started_at, finished_at
			 FROM jobs WHERE status = ?
			 ORDER BY priority DESC, created_at ASC LIMIT ?`, status, limit,
		)
	}
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var jobs []Job
	for rows.Next() {
		j, err := scanJob(rows)
		if err != nil {
			return nil, err
		}
		jobs = append(jobs, *j)
	}
	return jobs, rows.Err()
}

// CancelJob sets a pending or running job to "cancelled".
func CancelJob(db *sql.DB, id string) error {
	_, err := db.Exec(
		`UPDATE jobs SET status = 'cancelled', finished_at = CURRENT_TIMESTAMP
		 WHERE id = ? AND status IN ('pending','running')`, id,
	)
	return err
}

// ── Knowledge: Claims ─────────────────────────────────────────────────────────

// ClaimRow mirrors the claims table for CRUD operations.
type ClaimRow struct {
	ID          string
	BookID      string
	Chapter     int
	Paragraph   int
	SentenceIdx int
	Text        string
	ClaimType   string
	Confidence  float64
	Language    string
	CreatedAt   time.Time
}

// InsertClaim inserts a new claim row.
func InsertClaim(db *sql.DB, c ClaimRow) error {
	_, err := db.Exec(
		`INSERT INTO claims(id, book_id, chapter, paragraph, sentence_idx, text, claim_type, confidence, language)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		c.ID, c.BookID, c.Chapter, c.Paragraph, c.SentenceIdx, c.Text, c.ClaimType, c.Confidence, c.Language,
	)
	return err
}

// GetClaim retrieves a claim by ID.
func GetClaim(db *sql.DB, id string) (*ClaimRow, error) {
	row := db.QueryRow(
		`SELECT id, book_id, chapter, paragraph, sentence_idx, text, claim_type, confidence, language, created_at
		 FROM claims WHERE id = ?`, id,
	)
	var c ClaimRow
	if err := row.Scan(&c.ID, &c.BookID, &c.Chapter, &c.Paragraph, &c.SentenceIdx,
		&c.Text, &c.ClaimType, &c.Confidence, &c.Language, &c.CreatedAt); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &c, nil
}

// ListClaims returns all claims for a book, optionally filtered by chapter (0 = all).
func ListClaims(db *sql.DB, bookID string, chapter int) ([]ClaimRow, error) {
	var (
		rows *sql.Rows
		err  error
	)
	if chapter == 0 {
		rows, err = db.Query(
			`SELECT id, book_id, chapter, paragraph, sentence_idx, text, claim_type, confidence, language, created_at
			 FROM claims WHERE book_id = ? ORDER BY chapter, paragraph, sentence_idx`,
			bookID,
		)
	} else {
		rows, err = db.Query(
			`SELECT id, book_id, chapter, paragraph, sentence_idx, text, claim_type, confidence, language, created_at
			 FROM claims WHERE book_id = ? AND chapter = ? ORDER BY paragraph, sentence_idx`,
			bookID, chapter,
		)
	}
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	return scanClaims(rows)
}

// DeleteClaim removes a claim and its relations.
func DeleteClaim(db *sql.DB, id string) error {
	_, err := db.Exec(`DELETE FROM claims WHERE id = ?`, id)
	return err
}

func scanClaims(rows *sql.Rows) ([]ClaimRow, error) {
	var claims []ClaimRow
	for rows.Next() {
		var c ClaimRow
		if err := rows.Scan(&c.ID, &c.BookID, &c.Chapter, &c.Paragraph, &c.SentenceIdx,
			&c.Text, &c.ClaimType, &c.Confidence, &c.Language, &c.CreatedAt); err != nil {
			return nil, err
		}
		claims = append(claims, c)
	}
	return claims, rows.Err()
}

// ── Knowledge: Relations ──────────────────────────────────────────────────────

// RelationRow mirrors the claim_relations table.
type RelationRow struct {
	ID        string
	SourceID  string
	TargetID  string
	Relation  string
	Weight    float64
	CreatedAt time.Time
}

// InsertRelation inserts a claim relation.
func InsertRelation(db *sql.DB, r RelationRow) error {
	_, err := db.Exec(
		`INSERT INTO claim_relations(id, source_id, target_id, relation, weight)
		 VALUES (?, ?, ?, ?, ?)`,
		r.ID, r.SourceID, r.TargetID, r.Relation, r.Weight,
	)
	return err
}

// GetRelations returns all relations for a source claim.
func GetRelations(db *sql.DB, sourceID string) ([]RelationRow, error) {
	rows, err := db.Query(
		`SELECT id, source_id, target_id, relation, weight, created_at
		 FROM claim_relations WHERE source_id = ?`, sourceID,
	)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	var rels []RelationRow
	for rows.Next() {
		var r RelationRow
		if err := rows.Scan(&r.ID, &r.SourceID, &r.TargetID, &r.Relation, &r.Weight, &r.CreatedAt); err != nil {
			return nil, err
		}
		rels = append(rels, r)
	}
	return rels, rows.Err()
}

// ── Knowledge: Concepts ───────────────────────────────────────────────────────

// ConceptRow mirrors the concepts table.
type ConceptRow struct {
	ID       string
	Label    string
	Language string
	Aliases  string // JSON array
}

// InsertConcept inserts a concept.
func InsertConcept(db *sql.DB, c ConceptRow) error {
	_, err := db.Exec(
		`INSERT OR IGNORE INTO concepts(id, label, language, aliases) VALUES (?, ?, ?, ?)`,
		c.ID, c.Label, c.Language, c.Aliases,
	)
	return err
}

// LinkConceptClaim links a concept to a claim.
func LinkConceptClaim(db *sql.DB, conceptID, claimID string) error {
	_, err := db.Exec(
		`INSERT OR IGNORE INTO concept_claims(concept_id, claim_id) VALUES (?, ?)`,
		conceptID, claimID,
	)
	return err
}

// ── Knowledge: Epistemic state ────────────────────────────────────────────────

// UpsertEpistemicState inserts or replaces the epistemic state blob for a book.
func UpsertEpistemicState(db *sql.DB, id, bookID, dataJSON string, version int) error {
	_, err := db.Exec(
		`INSERT INTO epistemic_states(id, book_id, version, data)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(book_id) DO UPDATE SET
		   version = excluded.version,
		   data = excluded.data,
		   updated_at = CURRENT_TIMESTAMP`,
		id, bookID, version, dataJSON,
	)
	return err
}

// GetEpistemicState returns the epistemic state for a book.
func GetEpistemicState(db *sql.DB, bookID string) (id, dataJSON string, version int, err error) {
	row := db.QueryRow(
		`SELECT id, data, version FROM epistemic_states WHERE book_id = ?`, bookID,
	)
	err = row.Scan(&id, &dataJSON, &version)
	if err == sql.ErrNoRows {
		err = nil
	}
	return
}

// ── Stage progress ────────────────────────────────────────────────────────────

// MarkStageComplete records that stage stageName completed for jobID.
// Idempotent — safe to call multiple times for the same (job, stage) pair.
func MarkStageComplete(db *sql.DB, jobID, stageName string) error {
	_, err := db.Exec(
		`INSERT OR IGNORE INTO stage_progress(job_id, stage_name) VALUES (?, ?)`,
		jobID, stageName,
	)
	return err
}

// CompletedStages returns the set of stage names that have been completed for jobID.
// Returns an empty map (not nil) when the job has no completed stages.
func CompletedStages(db *sql.DB, jobID string) (map[string]bool, error) {
	rows, err := db.Query(
		`SELECT stage_name FROM stage_progress WHERE job_id = ?`, jobID,
	)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	result := make(map[string]bool)
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		result[name] = true
	}
	return result, rows.Err()
}

// scanner is implemented by both *sql.Row and *sql.Rows.
type scanner interface {
	Scan(dest ...any) error
}

func scanJob(s scanner) (*Job, error) {
	var j Job
	var result, errStr sql.NullString
	var startedAt, finishedAt sql.NullTime
	if err := s.Scan(
		&j.ID, &j.Type, &j.BookDir, &j.ChapterNum, &j.Payload,
		&j.Status, &j.Priority, &j.Batch,
		&result, &errStr, &j.Attempt, &j.MaxAttempts,
		&j.CreatedAt, &startedAt, &finishedAt,
	); err != nil {
		return nil, err
	}
	if result.Valid {
		j.Result = result.String
	}
	if errStr.Valid {
		j.Error = errStr.String
	}
	if startedAt.Valid {
		t := startedAt.Time
		j.StartedAt = &t
	}
	if finishedAt.Valid {
		t := finishedAt.Time
		j.FinishedAt = &t
	}
	return &j, nil
}
